- name: Copy app code to node.
  synchronize:
    src: "/home/ubuntu/spring3hibernate/"
    dest: "/home/ubuntu/"

- name: Nginx configuration
  become: yes
    template:
      src: default.tpl
      dest: /etc/nginx/sites-enabled/default
    notify: Restarting nginx

- name: maven clean package
  command: mvn -f /home/ubuntu/spring3hibernate/pom.xml clean package

- name: copy war file
  become: yes
  command: cp {{ remote_warfile }} {{ remote_webapps }}

