---
- name: Update the System Packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
 
- name: Create a Tomcat User
  user:
    name: tomcat
 
- name: Create a Tomcat Group
  group:
    name: tomcat
 
- name: Install JAVA
  become: yes
  apt:
    name: default-jdk
    state: present
 
 
- name: Create a Tomcat Directory
  become: yes
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes
 
- name: download & unarchive tomcat10
  become: yes
  unarchive:
    src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.4/bin/apache-tomcat- 10.0.4.tar.gz
    dest: /opt/tomcat10
    remote_src: yes
    extra_opts: [--strip-components=1]
 
- name: Change ownership of tomcat directory
  become: yes
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory
 
- name: Copy Tomcat service from local to remote
  become: yes
  copy:
    src: /etc/tomcat.service
    dest: /etc/systemd/system/
    mode: 0755
 
- name: Start and Enable Tomcat 10 on sever
  become: yes
  systemd:
    name: tomcat
    state: started
    daemon_reload: true