---
- name: Update the System Packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
 
- name: Create a Tomcat User
  become: yes
  user:
    name: tomcat
 
- name: Create a Tomcat Group
  become: yes
  group:
    name: tomcat
 
- name: Install JAVA
  become: yes
  apt:
    name: default-jdk
    state: present
 
 
- name: Create a Tomcat Directory
  become: yes
  file:
    path: /opt/tomacat8
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes
 
- name: download & unarchive tomacat8
  become: yes
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
    dest: /opt/tomcat8
    remote_src: yes
    extra_opts: [--strip-components=1]
 
- name: Change ownership of tomcat directory
  become: yes
  file:
    path: /opt/tomacat8
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory
 
- name: Creating a service file
  become: yes
  copy: 
    content: |-
      [Unit]
      Description=Tomcat Service
      Requires=network.target
      After=network.target
      [Service]
      Type=forking
      User=tomcat
      Environment="CATALINA_PID=/opt/tomcat8/logs/tomcat.pid"
      Environment="CATALINA_BASE=/opt/tomcat8"
      Environment="CATALINA_HOME=/opt/tomcat8"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      ExecStart=/opt/tomcat8/bin/startup.sh
      ExecStop=/opt/tomcat8/bin/shutdown.sh
      Restart=on-abnormal
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/tomcat.service

- name: Start and Enable Tomcat 8 on sever
  become: yes
  systemd:
    name: tomcat
    state: started
    daemon_reload: true